姓名: C/C++CI

在……之上:
推:
分支机构: [ "主" ]
pull_request:
分支机构: [ "主" ]

工作:
建立:

连续的: Ubuntu-最新

步骤:
    - uses: 操作/结帐@v4
    - 姓名: 配置
跑: ./configure
    - 姓名: 使
跑: 使
    - 姓名: 进行检查
跑: 进行检查
    - 姓名: 进行distcheck
跑: 进行distcheck
